---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: cloudprovider-quotacheck-job-
spec:
  template:
    spec:
      serviceAccountName: cloudprovider-quotacheck
      containers:
      - name: worker
        image: quay.io/jpacker/cloud-provider-quota-check@sha256:d608f8de34b5ab056ddc58d478d449d761efa59b289d4dddc311902ea65e6e22
        command: ['python','main.py']
        env:
        - name: PYTHONWARNINGS
          value: "ignore:Unverified HTTPS request"
        - name: CM_THRESHOLD
          value: "85"             # Threshold percentage. When usage exceeds a Kube warning event is fired
      restartPolicy: OnFailure