---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloudprovider-quotacheck-cronjob
spec:
  # Time is measured in coordinated universal time (UTC)
  #          ┌───────────── minute (0 - 59)
  #          │  ┌───────────── hour (0 - 23)
  #          │  │ ┌───────────── day of the month (1 - 31)
  #          │  │ │ ┌───────────── month (1 - 12)
  #          │  │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
  schedule: "59 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cloudprovider-quotacheck
          containers:
          - name: worker
            image: quay.io/jpacker/cloud-provider-quota-check:0.2
            command: ['python','main.py']
            env:
            - name: PYTHONWARNINGS
              value: "ignore:Unverified HTTPS request"  
          restartPolicy: OnFailure