---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloudprovider-quotacheck-cronjob
spec:
  # Time is measured in coordinated universal time (UTC)
  #          ┌───────────── minute (0 - 59)
  #          │  ┌───────────── hour (0 - 23)
  #          │  │ ┌───────────── day of the month (1 - 31)
  #          │  │ │ ┌───────────── month (1 - 12)
  #          │  │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
  schedule: "59 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cloudprovider-quotacheck
          containers:
          - name: worker
            image: quay.io/jpacker/cloud-provider-quota-check@sha256:d608f8de34b5ab056ddc58d478d449d761efa59b289d4dddc311902ea65e6e22
            command: ['python','main.py']
            env:
            - name: PYTHONWARNINGS
              value: "ignore:Unverified HTTPS request"
            - name: CM_THRESHOLD
              value: "85"             # Threshold percentage. When usage exceeds a Kube warning event is fired
          restartPolicy: OnFailure