---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: cloudprovider-quotacheck-job-
spec:
  template:
    spec:
      serviceAccountName: cloudprovider-quotacheck
      containers:
      - name: worker
        image: quay.io/jpacker/cloud-provider-quota-check:0.1
        command: ['python','main.py']
        env:
        - name: PYTHONWARNINGS
          value: "ignore:Unverified HTTPS request"  
      restartPolicy: OnFailure